Repository PoisotLab/ms_network_prediction, pull requests merged in 2020-11, with the labels that each got.

#32 adding forecasting figure
  figures/forecasting.png
Labels: figure

#36 adding my personal information to the metadata.json file
  metadata.json
Labels: housekeeping

#29 Update build system assets
  .assets/scripts/affiliations.py
  .assets/scripts/bibliography.py
  .assets/templates/_common.tex
  .assets/templates/_pandoc.tex
  .assets/templates/copyedit.tex
  .assets/templates/index.html
  .assets/templates/preprint.tex
  .github/workflows/compile.yml
  .gitignore
  README.md
Labels: housekeeping

#37 Add dom to metadata
  metadata.json
Labels: housekeeping

#42 Fix authorship in PDF
  .assets/templates/_common.tex
  .assets/templates/_list_authors.tex
  .assets/templates/_list_institutions.html
  .assets/templates/_single_institution.tex
  .assets/templates/copyedit.tex
  .assets/templates/index.html
  .assets/templates/style.css
Labels: housekeeping

#44 Add Gabriel's info to metadata
  metadata.json
Labels: housekeeping

#46 Add Norma to metadata
  metadata.json
Labels: housekeeping

#50 Community documents
  CONTRIBUTING.md
  LICENSE.md
Labels: housekeeping

#51 Update metadata.json
  metadata.json
Labels: housekeeping

#52 Add Benjamin to metadata
  metadata.json
Labels: housekeeping

#53 Conceptual Figure
  figures/conceptual.png
  figures/conceptual_svg.svg
Labels: figure

#6 What is the paper about?
  manuscript.md
  references.bib
Labels: integration, question, section 1

#8 What are the most important measures to predict?
  manuscript.md
  references.bib
Labels: integration, question, section 2

#30 Hypergraphs and multi-layers networks
  manuscript.md
  references.bib
Labels: integration, question, section 3

#24 Why predict networks before interactions?
  manuscript.md
Labels: drafting, question, section 1

#45 How much do networks vary in space?
  manuscript.md
Labels: drafting, question, section 4
