Repository PoisotLab/ms_network_prediction, pull requests merged in 2020-12, with the labels that each got.

#59 Everything is connected figure
  figures/everything_connected.png
  figures/everything_connected.svg
  figures/everything_connected_v2.png
  figures/everything_connected_v2.svg
Labels: figure, review

#34 What is the added value of using machine learning?
  manuscript.md
Labels: drafting, question, section 2

#49 What is the spatial scale suitable for the prediction of species interactions?
  manuscript.md
Labels: question, review, section 4

#47 Why do we need to predict interactions between species?
  manuscript.md
Labels: question, review, section 1

#20 How do we predict how species that have never co-occurred will interact?
  manuscript.md
Labels: question, review, section 3

#18 What ecological knowledge would forecasting bring?
  manuscript.md
Labels: question, review, section 5

#23 How do we predict what the species pool at a particular location is?
  manuscript.md
Labels: drafting, question, section 4

#11 How do we fit a predictive model?
  manuscript.md
Labels: question, review, section 2

#25 How could predictions for individual species, such as those used by IPBES/IUCN, be improved by considering ecological interactions?
  manuscript.md
Labels: question, review, section 4

#17 What is limiting our ability to predict network structure?
  manuscript.md
  references.bib
Labels: question, review, section 1

#19 How do we determine what interaction networks are feasible?
  manuscript.md
  references.bib
Labels: drafting, question, section 2

#41 What is interaction strength?
  manuscript.md
  references.bib
Labels: question, review, section 3

#54 Integrate section 1 into the main manuscript
  manuscript.md
  references.bib
Labels: integration, section 1

#55 Integrate section 2 into main manuscript
  manuscript.md
  references.bib
Labels: integration, section 2

#28 How do we validate a forecasting model, and can hindcasting help?
  manuscript.md
Labels: drafting, question, section 5

#56 Integrate section 3 into the main manuscript
  manuscript.md
Labels: integration, section 3

#35 How do we propagate uncertainty through a predictive model?
  manuscript.md
Labels: drafting, question, section 2
